[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "systems-manager"
version = "1.1.9"
description = "Systems Manager will update your system and install/upgrade applications. Additionally, as allow AI to perform these activities as an MCP Server"
readme = "README.md"
authors = [{ name = "Audel Rouhi", email = "knucklessg1@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Public Domain",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "requests>=2.28.1",
    "fastmcp>=2.11.3",
    "psutil>=7.0.0",
    "distro>=1.9.0",
]

[project.scripts]
systems-manager = "systems_manager.systems_manager:systems_manager"
systems-manager-mcp = "systems_manager.systems_manager_mcp:systems_manager_mcp"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
include-package-data = true
package-data = { "systems_manager" = ["systems_manager"] }
