[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "systems-manager"
version = "1.1.25"
description = "Systems Manager will update your system and install/upgrade applications. Additionally, as allow AI to perform these activities as an MCP Server"
readme = "README.md"
authors = [{ name = "Audel Rouhi", email = "knucklessg1@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Public Domain",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "requests>=2.28.1",
    "psutil>=7.0.0",
    "distro>=1.9.0",
]

[project.optional-dependencies]
mcp = [
    "fastmcp>=3.0.0b1",
    "eunomia-mcp>=0.3.10",
    "fastapi>=0.128.0"
]

a2a = [
    "pydantic-ai-slim[fastmcp,openai,anthropic,google,huggingface,a2a,ag-ui,web]>=1.32.0",
    "pydantic-ai-skills",
    "fastapi>=0.128.0"
]

all = [
    "fastmcp>=3.0.0b1",
    "eunomia-mcp>=0.3.10",
    "pydantic-ai-slim[fastmcp,openai,anthropic,google,huggingface,a2a,ag-ui,web]>=1.32.0",
    "pydantic-ai-skills",
    "fastapi>=0.128.0"
]

[project.scripts]
systems-manager = "systems_manager.systems_manager:systems_manager"
systems-manager-mcp = "systems_manager.systems_manager_mcp:systems_manager_mcp"
systems-manager-agent = "systems_manager.systems_manager_agent:agent_server"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
systems_manager = ["mcp_config.json", "skills/**"]

[tool.setuptools]
include-package-data = true
