[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "systems-manager"
version = "1.2.17"
description = "Systems Manager will update your system and install/upgrade applications. Additionally, as allow AI to perform these activities as an MCP Server"
readme = "README.md"
authors = [{ name = "Audel Rouhi", email = "knucklessg1@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Public Domain",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "agent-utilities>=0.2.4",
    "psutil>=7.0.0",
    "distro>=1.9.0",
]

[project.optional-dependencies]
mcp = [
    "agent-utilities[mcp]>=0.2.4",
]

agent = [
    "agent-utilities[agent,logfire]>=0.2.4",
]

all = [
    "agent-utilities[mcp,agent,logfire]>=0.2.4",
]

[project.scripts]
systems-manager = "systems_manager.systems_manager:systems_manager"
systems-manager-mcp = "systems_manager.mcp:mcp_server"
systems-manager-agent = "systems_manager.agent:agent_server"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
systems_manager = [ "mcp_config.json", "skills/**", "agent/**",]

[tool.setuptools]
include-package-data = true

[tool.codespell]
ignore-words-list = "fo"
